#include <clang/AST/ASTTypeTraits.h>
#include <clang/AST/CanonicalType.h>
#include <clang/AST/DataCollection.h>
#include <clang/ASTMatchers/ASTMatchersInternal.h>
#include <clang/Analysis/FlowSensitive/DataflowAnalysisContext.h>
#include <clang/Analysis/FlowSensitive/DataflowEnvironment.h>
#include <clang/Basic/Diagnostic.h>
#include <clang/Basic/PartialDiagnostic.h>
#include <clang/ExtractAPI/API.h>
#include <clang/Lex/HeaderSearch.h>
#include <clang/Sema/Overload.h>
#include <clang/Sema/ParsedAttr.h>
#include <clang/Sema/Sema.h>
#include <clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h>
#include <clang/StaticAnalyzer/Core/PathSensitive/SVals.h>
#include <clang/Tooling/Refactoring/RefactoringOptions.h>
#include <clang/Tooling/Transformer/RewriteRule.h>
#include <llvm/ADT/APFloat.h>
#include <llvm/ADT/AllocatorList.h>
#include <llvm/ADT/Any.h>
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/BitmaskEnum.h>
#include <llvm/ADT/DenseMap.h>
#include <llvm/ADT/DenseMapInfo.h>
#include <llvm/ADT/FoldingSet.h>
#include <llvm/ADT/FunctionExtras.h>
#include <llvm/ADT/Hashing.h>
#include <llvm/ADT/IntrusiveRefCntPtr.h>
#include <llvm/ADT/PriorityWorklist.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/STLFunctionalExtras.h>
#include <llvm/ADT/Sequence.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringRef.h>
#include <llvm/ADT/TinyPtrVector.h>
#include <llvm/ADT/TypeSwitch.h>
#include <llvm/ADT/bit.h>
#include <llvm/ADT/fallible_iterator.h>
#include <llvm/ADT/ilist_iterator.h>
#include <llvm/BinaryFormat/Dwarf.h>
#include <llvm/CodeGen/CodeGenPassBuilder.h>
#include <llvm/CodeGen/MachineInstrBundleIterator.h>
#include <llvm/CodeGen/MachinePassManager.h>
#include <llvm/Demangle/ItaniumDemangle.h>
#include <llvm/ExecutionEngine/Orc/Core.h>
#include <llvm/ExecutionEngine/Orc/Shared/ExecutorAddress.h>
#include <llvm/ExecutionEngine/Orc/Shared/SimplePackedSerialization.h>
#include <llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/DiagnosticInfo.h>
#include <llvm/IR/Metadata.h>
#include <llvm/IR/PassInstrumentation.h>
#include <llvm/IR/PassManager.h>
#include <llvm/IR/PassManagerInternal.h>
#include <llvm/Pass.h>
#include <llvm/Support/AllocatorBase.h>
#include <llvm/Support/Casting.h>
#include <llvm/Support/CheckedArithmetic.h>
#include <llvm/Support/CommandLine.h>
#include <llvm/Support/Error.h>
#include <llvm/Support/ErrorOr.h>
#include <llvm/Support/FormatProviders.h>
#include <llvm/Support/FormatVariadicDetails.h>
#include <llvm/Support/HashBuilder.h>
#include <llvm/Support/JSON.h>
#include <llvm/Support/MSVCErrorWorkarounds.h>
#include <llvm/Support/MathExtras.h>
#include <llvm/Support/SwapByteOrder.h>
#include <llvm/Support/TrailingObjects.h>
#include <llvm/Support/TypeSize.h>
#include <llvm/Support/YAMLTraits.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/Support/type_traits.h>
#include <llvm/Transforms/Scalar/LoopPassManager.h>
#include <llvm/XRay/Graph.h>
